---
name: CICD
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: code clone from github
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building docker container
        run: echo "Docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testig the container
        run: echo "Testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying the app
        run: echo "docker compose deployed the app"
