name: DevSecOps End to End Pipeline
on:
  workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: code-quality
              uses: ./.github/workflows/code-quality.yml
            - name: security-scan
              uses: ./.github/workflows/security-scan.yml
            - name: dependency-scan
              uses: ./.github/workflows/dependency-scan.yml
            - name: docker-lint-scan
              uses: ./.github/workflows/docker-lint.yml 
        
            