# uses trivy to scan docker images for vulnerabilities
name: Docker Image Scanner
on:
    workflow_call:

jobs:
    image-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: login to  Docker hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: scan docker image with trivy
              uses: aquasecurity/trivy-action@0.35.0
              with:       
                image-ref: ${{ vars.DOCKERHUB_USERNAME }}/github-actions-app:latest
                severity: 'CRITICAL,HIGH,MEDIUM'
                exit-code: '1'
                trivyignores: ${{ github.workspace }}/.trivyignore
