name: portfolio
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write


jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}
        steps: 
            # get access to the repository via prebuilt action
            # clones the rep where this workflow is defined and makes it available for the next steps
            - name: Checkout repository
              uses: actions/checkout@v4
            
            # setup git hub pages
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4
              
            # static code artifacts 
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
            
            # deploy to github pages
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
