#gitleaks 
name: Secrets Scan
on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetch all history for gitleaks to work properly

            - name: run gitleaks scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                # This token is automatically provided by GitHub Actions and
                # has permissions to read the repository's code and history.